name: my-first-workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Multiline Command
              run: | 
                echo "my first message"
                ls -ltr
                cat README.md
            
            - name: create ASCII artwork
              run: cowsay -f cat "i am a cat" >> cat.txt



            # - name: list files
            #   run: ls

            # - name: read file
            #   run: cat README.md
