name: Generate ASCII Art

on: push

jobs:
    generate_ascii_art:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Install 
              run: sudo apt-get install cowsay

            - name: create ASCII artwork
              run: cowsay -f dragon "i am a dragon" >> dragon.txt

            - name: list files
              run: ls -ltra

            - name: read file
              run: cat dragon.txt

