name: Generate ASCII art

on: push

jobs:
    exceuting_shell_script:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Executing Shell Script
              run: |
               chmod 744 ascii-script.sh
               ./ascii-script.sh

